name: electricity_consumption_tracker
description: A Flutter app to track electricity consumption with data storage and analysis.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.5.0 # Hlavní knihovna Drift
  sqflite: ^2.2.0
  path_provider: ^2.0.14 # Ukládání dat na zařízení uživatele

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.5.0 # Generování kódu pro Drift
  build_runner: ^2.3.3 # Potřebný nástroj pro generování kódu

flutter:
  uses-material-design: true
