name: electricity_consumption_tracker
description: A Flutter app for tracking electricity consumption.

publish_to: "none" # Zabrání publikování na pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Ujisti se, že odpovídá požadavkům závislostí

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.9.0 # Hlavní knihovna pro práci s databází
  sqlite3_flutter_libs: ^0.5.0 # SQLite implementace
  path_provider: ^2.0.0 # Získávání cesty k souborům
  path: ^1.8.3 # Práce s cestami k souborům
  drift_flutter: ^0.2.1
  intl: ^0.20.1
  provider: ^6.1.2
  fl_chart: ^0.69.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter # Testovací závislosti
  drift_dev: ^2.9.0 # Drift code generator
  build_runner: ^2.4.5 # Generátor kódu

flutter:
  uses-material-design: true
